services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # UI de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - network_trabalho_final
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres_custom
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api_messaging
    networks:
      - network_trabalho_final

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_trabalho_final
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - network_trabalho_final

  auth-api:
    build:
      context: ./auth_api/
      dockerfile: Dockerfile
    container_name: auth_api
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
    networks:
      - network_trabalho_final

  record-api:
    build:
      context: ./record-api/ 
      dockerfile: Dockerfile
    container_name: record_api
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
      - redis  
    environment:
      DATABASE_URI: postgresql://root:secret@postgres:5432/api_messaging
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - network_trabalho_final
  
  receive-send-api:
    build:
      context: ./receive-send-api/ 
      dockerfile: Dockerfile
    container_name: receive_send_api
    ports:
      - "3000:3000" 
    depends_on:
      - auth-api 
      - record-api 
      - rabbitmq
      - redis
    environment:
      PORT: 3000
      RECORD_API_BASE_URL: http://record-api:8080
      AUTH_API_BASE_URL: http://auth_api:80
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - network_trabalho_final

volumes:
  redisdata:
  postgresdata:
  rabbitmq_data:

networks:
  network_trabalho_final:
    driver: bridge
