version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: mensageria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build: .
    container_name: receive-send-api
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:senha123@postgres:5432/mensageria
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && node src/server.js"

volumes:
  postgres_data:
