version: '3.8'
services:
  postgres:
      build:
        context: ./database
        dockerfile: Dockerfile
      container_name: postgres_custom
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./sql:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: api_messaging
      networks:
        - network_trabalho_final

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network_trabalho_final

volumes:
  redisdata:
  postgresdata:

networks:
  network_trabalho_final:
    driver: bridge
    