version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: realuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api_messaging
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  record-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: record_api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis

volumes:
  pg_data:
  redis_data:
